### ISSUE TITLE
Settings overview in breadcrumbs modal shows the wrong numbers

### ISSUE THREAD

**Issue by ethanjli** [pez-globo/pufferfish-vent-software#307]
The "HFNC Control" screen of the Ventilation Controls breadcrumbs modal shows the wrong numbers in its black panels. The Heart Rate panel's measurement appears to be stuck at 0 (instead of showing the sensor data which is shown by the Heart Rate panel on the dashboard), while the SpO2 shows rapidly-flickering unfiltered measurements (instead of showing the filtered data which is shown by the SpO2 panel on the dashboard). 

Unsaved changes to alarm limits are not reflected in the small numbers on the upper right corners of the alarm limits panels.
I think the FiO2 and Flow Rate panels should show the settings as the big numbers; right now it looks like they're configured to show the actual sensor measurements.

**Software:**
 - Domain: frontend
 - Version: I see this on https://github.com/pez-globo/pufferfish-software/tree/feature/firmware-log-events (e.g. on commit d0d5436), but I suspect it should be reproducible on develop.

**Additional context**
I am testing with ventserver.application, but I expect this would be reproducible with ventserver.simulation too.

**Comment by ethanjli** [comment]
We might be able to show unsaved changes to ParametersRequest and AlarmLimitsRequest if we commit all increment/decrement operations to ParametersRequestStandby and AlarmLimitsRequestStandby. In this case, we should probably rename "Standby" to "Draft" (e.g. "ParametersRequestDraft").

**Comment by rohanpurohit** [comment]
after #338 unsaved changes to alarm limits are visible in the HFNC control alarm limit panels, but only in the `dashboard` page, since we decided we would commit changes from increment/decrement buttons to AlarmLimitsRequestStandby which is now AlarmLimitsRequestDraft. In a scenario where we are on the alarm limits screen and open the events log and then the alarm limits modal to make changes, on making changes and pressing `submit` everything is as expected, But if we make changes and press `cancel` and `confirm`, we find ourselves also losing the `unsaved` changes on the alarm limits screen if any, as the changes made in alarm limits screen and breadcrumbs modal are independent. thus it would be easier if we propagate the unsaved changes in the alarm limits screen to the breadcrumbs modal and vice-versa
