### ISSUE TITLE
cobs exceptions on running backend server

### ISSUE THREAD

**Issue by rohanpurohit** [pez-globo/pufferfish-vent-software#315]
When the backend server was started in a development environment on a ventilator unit that had previously been deployed with a fairly older version of the software (both on the stm32 micro-controller and raspberry pi)
continuous exceptions related to COBS decoding were encountered, the exact stack trace isn't available

**To Reproduce**
1. cd backend
2. run 'poetry run python3 -m ventserver.application
3. console should output continuous exceptions about COBS decoding errors mainly 'invalid length..'

**Expected behavior**
there shouldn't be any exceptions

**Device (please complete the following information):**
 - This was run on a ventilator unit with raspberry pi 4B and STM32 NUCLEO-H743Z12

**Software (please complete the following information):**
- frontend/backend/firmware - 8a444caee13b6e0728c960981acd013fc799807e
- (previously deployed) frontend/backend/firmware - e1ec05de2d621cdebeb1b63b471dce5ab7a0c31b

**Additional context**
The bug has not been reproduced on different units with a clean environment for raspberry pi.

**Comment by ethanjli** [comment]
Because we've been unable to reproduce this behavior despite lots of regular testing, and it seems quite possible that it was from a mismatched software configuration (and time pressures at the time of observation of this issue prevented software configuration from being managed cleanly), I'm going to close this issue. We can reopen it if we observe it again.
